package io.pzstorm.installer.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class InstallerWindowGUI extends JFrame {

	public JPanel mainPanel;
	private JPanel logoPanel;
	private JLabel logoIcon;
	private JPanel bottomPanel;

	public InstallerWindowGUI() {

		$$$setupUI$$$();
		setContentPane(mainPanel);
		setTitle("Storm Installer");
		setSize(600, 500);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setVisible(true);
	}

	public static void main(String[] args) {

		InstallerWindowGUI window = new InstallerWindowGUI();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {

		mainPanel = new JPanel();
		mainPanel.setLayout(new FormLayout("fill:d:grow", "center:150px:noGrow,fill:d:grow"));
		mainPanel.setAlignmentX(0.5f);
		mainPanel.setAlignmentY(0.5f);
		mainPanel.setBackground(new Color(-16777216));
		mainPanel.setForeground(new Color(-16777216));
		mainPanel.setMinimumSize(new Dimension(600, 200));
		mainPanel.setOpaque(false);
		mainPanel.setPreferredSize(new Dimension(600, 500));
		logoPanel = new JPanel();
		logoPanel.setLayout(new FormLayout("center:d:grow", "center:d:grow"));
		logoPanel.setAlignmentX(0.0f);
		logoPanel.setAlignmentY(0.0f);
		logoPanel.setAutoscrolls(false);
		logoPanel.setBackground(new Color(-14604221));
		logoPanel.setMinimumSize(new Dimension(1, 1));
		logoPanel.setPreferredSize(new Dimension(100, 150));
		CellConstraints cc = new CellConstraints();
		mainPanel.add(logoPanel, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.TOP));
		logoIcon = new JLabel();
		logoIcon.setAlignmentX(0.5f);
		logoIcon.setAlignmentY(0.5f);
		logoIcon.setHorizontalAlignment(0);
		logoIcon.setHorizontalTextPosition(0);
		logoIcon.setIcon(new ImageIcon(getClass().getResource("/storm-logo.png")));
		logoIcon.setText("");
		logoPanel.add(logoIcon, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
		bottomPanel = new JPanel();
		bottomPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
		bottomPanel.setAlignmentX(0.5f);
		bottomPanel.setBackground(new Color(-14604221));
		bottomPanel.setDoubleBuffered(false);
		bottomPanel.setEnabled(true);
		bottomPanel.setForeground(new Color(-16777216));
		bottomPanel.setMinimumSize(new Dimension(1, 1));
		bottomPanel.setPreferredSize(new Dimension(600, 300));
		mainPanel.add(bottomPanel, cc.xy(1, 2, CellConstraints.DEFAULT, CellConstraints.FILL));
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() {

		return mainPanel;
	}
}
